export const MAX_ACTIVE_PRODUCT_TYPES_PER_USER = 500;
export const MAX_ARCHIVED_PRODUCT_TYPES_PER_USER = 250;
export const MAX_PRODUCT_TYPE_SEARCH_RESULTS = 25;
export const MAX_ACTIVE_INVENTORY_LOTS_PER_USER = 1000;
export const MAX_ARCHIVED_INVENTORY_LOTS_PER_USER = 250;
export const MAX_INVENTORY_LOTS_PER_PRODUCT_TYPE = 500;
export const MAX_SHOPPING_CHECKOUT_ITEMS = 50;
